[package]
name = "bitverify"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.29.0", features = ["rand", "rand-std", "hashes"] }
bitcoin = "0.32.2"
bitcoin_hashes = "0.14.0"
base64 = "0.22.1"